version: 2.1

jobs:
  rust-ci:
    docker:
      - image: cimg/rust:1.85
    steps:
      - checkout

      - restore_cache:
          keys:
            - cargo-v1-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-v1-

      - run:
          name: Install nightly toolchain and components
          command: |
            rustup update nightly
            rustup component add rustfmt clippy --toolchain nightly

      - run:
          name: Fetch dependencies
          command: cargo fetch

      - save_cache:
          key: cargo-v1-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git

      - run:
          name: Check formatting
          command: cargo fmt --all -- --check

      - run:
          name: Run clippy
          command: cargo clippy --all-targets --all-features -- -D warnings

      - run:
          name: Run tests
          command: cargo test --all-targets

workflows:
  version: 2
  ci:
    jobs:
      - rust-ci
