name: All Contributors

on:
  issue_comment:
    types: [created, edited]

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@all-contributors')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 100
          auto_detect_branch_protection: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
